[project]
name = "WebAlgebra"
version = "0.1.0"
description = "Composable RDF operations in JSON"

authors = [
  { name = "Martynas Jusevicius", email = "martynas@atomgraph.com" }
]
requires-python = ">=3.10"
dependencies = [
    "rdflib>=7.0.0",
]

[tool.poetry]
name = "WebAlgebra"
version = "0.1.0"
description = "Composable RDF operations in JSON"
authors = ["Martynas Jusevicius <martynas@atomgraph.com>"]
packages = [{ include = "web_algebra", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
rdflib = "7.0.0"
openai = "*"
mcp = { version = "1.9.1", extras = ["cli"] }
pydantic-settings = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
